md "Todos os Paises"
cd "Todos os Paises"
md "Argentina"
md "Bolivia"
md "Brasil"
md "Chile"
md "Colombia"
md "Equador"
md "Guiana"
md "Guiana Francesa"
md "Paraguai"
md "Peru"
md "Suriname"
md "Uruguai"
md "Venezuela"
cd "Brasil"
md "Alagoas"
md "Bahia"
md "Ceara"
md "Maranhao"
md "Paraiba"
md "Piaui"
md "Rio Grande do Norte"
md "Sergipe"
md "Acre"
md "Amapa"
md "Amazonas"
md "Para"
md "Rondonia"
md "Roraima"
md "Tocantins"
md "Parana"
md "Santa Cantarina"
md "Rio Grande do Sul"
md "Sao Paulo"
md "Rio de Janeiro"
md "Espirito Santo"
md "Minas Gerais"
cd..