md "Todos os Paises"
cd "Todos os Paises"
md "Argentina"
md "Bolivia"
md "Brasil"
md "Chile"
md "Colombia"
md "Equador"
md "Guiana"
md "Guiana Francesa"
md "Paraguai"
md "Peru"
md "Suriname"
md "Uruguai"
md "Venezuela"