md "Todos os clubes"
cd "Todos os clubes"
md "Serie A"
md "Serie B"
cd "Serie A"
md "AtleticoMG"
md "Palmeiras"
md "Forteleza"
md "Bragantino"
md "Flamengo"
md "AthleticoPR"
md "AtleticoGO"
md "Ceara"
md "Internacional"
md "Santos"
md "Corinthians"
md "Juventude"
md "Bahia"
md "Sao Paulo"
md "Fluminense"
md "Cuiba"
md "Sport"
md "AmericaMG"
md "Gremio"
md "Chapecoense"
cd..